title: 'OutWrest.github.io'
description: "Description test"
baseurl: "/"
url: "https://OutWrest.github.io"

header_pages:
  - index.md
  - README.md
  - about.md
  - contact.md

style: dark

footer: '<a href="https://ctftime.org/team/116013">CTFTime</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console